# Generated by Django 4.1.4 on 2022-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbcrudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbcrudmodel',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fbcrudmodel',
            name='fbvimg',
            field=models.ImageField(null=True, upload_to='fbv-img/'),
        ),
    ]
