# Generated by Django 4.1.4 on 2022-12-23 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fbcrudapp', '0002_fbcrudmodel_datetime_fbcrudmodel_fbvimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbcrudmodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
