# Generated by Django 4.1.4 on 2022-12-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ariticle',
            new_name='Article',
        ),
    ]
