# Generated by Django 4.1.4 on 2022-12-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app', '0002_rename_ariticle_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
    ]
