# Generated by Django 4.1.4 on 2022-12-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cemail', models.EmailField(max_length=200)),
                ('cmessage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
