# Generated by Django 4.1.4 on 2022-12-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app', '0005_contactinfo_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'AllContactInfo'},
        ),
    ]
