# Generated by Django 4.1.4 on 2022-12-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app', '0006_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'All Contact Info'},
        ),
    ]
