# Generated by Django 4.1.4 on 2022-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbvCrudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('cbvdate', models.DateField(auto_now_add=True)),
                ('cbv_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
