# Generated by Django 4.1.4 on 2022-12-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvcrudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbvcrudmodel',
            options={'verbose_name': 'CBV CRUD', 'verbose_name_plural': 'CBV CRUD Models'},
        ),
        migrations.AlterField(
            model_name='cbvcrudmodel',
            name='cbvdate',
            field=models.DateField(),
        ),
    ]
