# Generated by Django 4.1.4 on 2022-12-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Persons'},
        ),
    ]
