# Generated by Django 4.1.4 on 2022-12-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app2', '0002_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbvArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'CbvArticles',
            },
        ),
    ]
