# Generated by Django 4.1.4 on 2022-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2app2', '0003_cbvarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbvContactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbvname', models.CharField(max_length=200)),
                ('cbvemail', models.EmailField(max_length=254)),
                ('cbvmessage', models.TextField()),
            ],
        ),
    ]
